gtfs_rt_public_endpoint_name: 'VBB GTFS-RT Feed'

# see also https://gist.github.com/derhuerst/f0b6c9cf28b90746770464eb8e5b918f
gtfs_rt_number_of_schedule_feed_variants: 1

# VPN-internal IP & port of (their) VBB Datendrehscheibe
# These need to be defined for *all* hosts in `staging` because `gtfs_rt_converter` machines need them too.
vdv_453_api_host: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36636437393135366134343930656563613532386439383636636235363830383265623965626634
          3833613031636261323866656136363838326561643636390a343535363038373836393030336634
          39386339616235383638386161613665333236653461373634323337336538316236393261613361
          3266643461326430610a653531666634376233303533626161643732396236333331303035313034
          6439
vdv_453_api_port: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31383766303738626163306161643035353965343933643838656264333765653264366339306639
          6235333161303566333263663833383839376532363265350a356134373938323137366430316337
          35326531393532343332626364663335653739343436643564303635396234663264323232366162
          3537663462643566650a653766633864366464353364346561643933396138353638653531363335
          3463
