gtfs_rt_public_endpoint_name: 'VBB GTFS-RT Feed (staging)'

# see also https://gist.github.com/derhuerst/f0b6c9cf28b90746770464eb8e5b918f
gtfs_rt_number_of_schedule_feed_variants: 3

# VPN-internal IP & port of (their) VBB Datendrehscheibe
# These need to be defined for *all* hosts in `staging` because `gtfs_rt_converter` machines need them too.
vdv_453_api_host: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62336337656265356331643937303732356338316133313861643931636632376364623830656366
          3334343866373034316135383738383463663163313739640a626233666436626333633965393065
          37663338383263633530656232633763356263323238306365323439626335663432363332396639
          3432616634633335340a383730336663656263326432346335363036313966333837646163636636
          3430
vdv_453_api_port: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31383766303738626163306161643035353965343933643838656264333765653264366339306639
          6235333161303566333263663833383839376532363265350a356134373938323137366430316337
          35326531393532343332626364663335653739343436643564303635396234663264323232366162
          3537663462643566650a653766633864366464353364346561643933396138353638653531363335
          3463

# Note: We force HTTPS so that HTTP Basic Auth is secure.
grafana_public_endpoints:
- 'https://staging.gtfsrt.vbb.de:8080'
- 'https://staging.vbb-gtfs-rt.jannisr.de:8080'

# Grafana HTTP basic auth
grafana_basic_auth_user: admin
# hashed & salted using `caddy hash-password`
grafana_basic_auth_password_caddy_hashed: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35663433626566653739363831333264643862303932633632333338393534343635623733633063
          3431663132336364623431343735323837393363393733610a313534333262316332373533666163
          32316130316135613937346537343537313631373663343133386230373337366561346565386230
          6261666266323631310a613033613536656133626232663934393530636266626465663631313865
          64366635353338666336663630333437323762353337366563343030326164353435663837376434
          61613966303161326431656132356134326438323236383130336238313061386433326132616164
          376339346138386338393161366539343233

grafana_admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64623764383264363363333266323933396364356632653237613236313566343933653362633330
          3033623435366464366465323732616438306233366365360a316131333432326236366633343261
          61363366343837623035653832363033383135356236383934323765653465316630333863623164
          3233383361663437650a643964636632333562373739626136336364383835313562666634323439
          37663832656566386663616161623435666265303131343734666565363535353730
grafana_user_vbb_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39346261363935613836666333633662393835373963303564663036623034623638303931326335
          3635623432346630306365396630613034376135343739370a323938626430363330326433343337
          61356464653830643838333832353663646163393931343537373131613466353065613566623737
          3066643164316666610a636361336631343036643662633263306134633866316439306531306265
          65303633363666626430363632366164303932356637333232343563656264333736
grafana_user_vbb_email: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39303433323933393733623433316239333633386532363234343561333037393566313830316234
          3664393464356230353439326666306333363438626262660a326634303232333762626563346461
          31323764633564623933316635346630373933356330306338666634373237613732356339356438
          3238366132653961360a333933626139393534373761643538353365653563623434313537646364
          33663166623562633062653430653665623531386639393637343231643831333063
grafana_user_marzieh_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63356133363564323832343164623033333235373065336336373762666334336633333938666535
          3333653931653237313434663138373061653034353439310a616237366338333562313762643439
          63356430346636373666303930346663393539623933623335663734303236353365633839633964
          6165636535316235650a383834303461313961356537363737366238376231626263373533346165
          33363732653731613164393861623030663135383331336432393335636233303963
grafana_user_marzieh_email: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34326561666136363164663166353931313835333837623130323962323866623736366266643539
          3762303536333437646233633330316363363634353662300a333837646364386330303739366232
          32383031313438613232303561333933383739316337393538333833333861643061316638356238
          3933373930346237300a623430393734633834623762323138626531303537326638353437623463
          35386637393339646561333562623836633238666262303934656461633330623837

alerts_public_transport_slack_webhook: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34656538393139386631616633373131636536386534643337626565316465353134326666333637
          3931626232336539666132363161326561343031626135650a346636646564616265386637613861
          31343830616162393735333834366262633938326136623664356337393732356565303762333066
          6233623336643535620a323461303038656161636464363937626265386631323032623639626265
          65313530663634653332316430633362613365656461373364393064663762356136666338636633
          63313566626630316363633730343533666361663363656634663463356666356634323832316339
          34383965373966623461353438323564353332636631623665663836373866373262663438333064
          38646130616461393734
