# Because vbb_gtfs_rt_converter_staging runs on special infrastructure, we hide its SSH credentials from the public.
ansible_host: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33396337393265393733336339643932366539333662366364363264663465333838643230343331
          3431346532363334353366313863646463313331333166650a363838366161346635373932376662
          34363638353265363439316337313039656661346439643434373532386161306636616631343061
          6332303233383861380a643531363430393530333765613531666166613934613239316132353864
          3735
ansible_user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34306564376462363637636331373863346232356231383862363938343962396231306336396634
          6562633935346462326361303638616635386436323963660a663637386431363561643264646164
          39343336313038373639616664353336663063393535353866636662323565386330383239656139
          6361363065386263340a633063313238333162616532316661376534313564643834633761313437
          3438

wireguard_private_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30323230633665666631303137666363393932393264383062303836303662393537386238383464
          6539353265373737656339646534613833366136356564630a636136336234643237313264656165
          37646366323236663831343936366231626639626138336430666563353531616466613230633466
          6163343864343761360a633338393634626234313230303137663931363436613164613339326633
          33333761343439613938623330313362636166613830333537613630646434383036393266663761
          6264643563336461353431643661303537613938343632323462

wireguard_addresses:
  - '10.0.0.0/24'
# wireguard_allowed_ips: '10.0.0.0/24'
# vbb_gtfs_rt_converter_staging is behind NAT.
wireguard_endpoint: ''

# todo: don't hard-code these
# the VPN-internal address of vbb-datendrehscheibe-proxy-staging, as seen from vbb-gtfs-rt-converter-staging
vdv_453_nats_adapter_address: '10.0.0.1'
# the VPN-internal address of gtfs-rt-converter-staging
gtfs_rt_converter_address: '10.0.0.0'
# the VPN-internal address of gtfs-rt-server-staging, as seen from gtfs-rt-converter-staging
gtfs_rt_server_address: '10.0.0.2'
gtfs_rt_metrics_service_address: '10.0.0.2'

postgresql_major_version: 17
