wireguard_private_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39633661633636383165626565346637326661393035623134646633313835356431613030643337
          6262633061663632363139396432396636313162643236340a316133366238333261666536323439
          39323737653739366232373537656161343035376162663232653230663162353365313833653935
          3637663762376134620a313733666366346336306463656437346536613435343531626132663331
          33386262643366373836363034643133663439656338333334393731623563666439313435646662
          3663366537396136313137323763386139376364663937366436

wireguard_addresses:
  - '10.0.0.0/24'
# wireguard_allowed_ips: '10.0.0.0/24'

# todo: don't hard-code these
# In the production system, vbb_gtfs_rt_converter_production (running Prometheus) and vbb_gtfs_rt_server_production (running nats-consuming-gtfs-rt-server) are on the same machine.
gtfs_rt_converter_address: '10.0.0.0'
gtfs_rt_server_address: '10.0.0.0'
gtfs_rt_metrics_service_address: '10.0.0.0'
# the VPN-internal address of vbb_datendrehscheibe_proxy_production, as seen from vbb_gtfs_rt_production
vdv_453_nats_adapter_address: '10.0.0.1'

# see also https://caddyserver.com/docs/caddyfile/concepts#addresses
# Note: The first URL gets used for the explainer HTML page.
gtfs_rt_public_endpoints:
- 'https://production.gtfsrt.vbb.de'
- 'https://production.vbb-gtfs-rt.jannisr.de'
- 'http://95.217.148.26:80' # todo: pull from ansible facts?
- 'http://[2a01:4f9:3080:3505::2]:80' # todo: pull from ansible facts?

# Note: We force HTTPS so that HTTP Basic Auth is secure.
grafana_public_endpoints:
- 'https://production.gtfsrt.vbb.de:8080'
- 'https://production.vbb-gtfs-rt.jannisr.de:8080'

# Grafana HTTP basic auth
grafana_basic_auth_user: admin
# hashed & salted using `caddy hash-password`
grafana_basic_auth_password_caddy_hashed: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64396136363861636636303763376532316165663163313335326661663732643131376562323262
          6539356464366563373933663736333236613066303635360a366133636139383136373331646464
          37633762366330636262666531653435366666343832383334316437633765636164303565356531
          3031323630356636610a663138666430306162613639613166613761613734636665336138663133
          64646261623265343136613765393261643531616533656635656332303163333062653063636463
          62366562376534323966663435323536613761643139383230633365393864393739396363313463
          383864666634666438386463656232643937

grafana_admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38303032346632613632316332303265343166613266663931636433313230346464323633613137
          3666643039653264653939356635613031316132313361630a363037373461643437646132616562
          31656361383963613432323762623439636438646232343063343031336636663333356633336137
          3837653464616231610a633037363733343931353038616239613234336236663163636239616564
          63343830653861353131633133353866316434303764663336343763613730306164
grafana_user_vbb_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37663062316632323733303464346632373262623131613466343231393935663665653739363035
          3233313636303234633338336633613964393262396534380a363835613839626265616233363635
          64613262386261386236646264346464643266386330353238643336363435316663323332306265
          6166626139393939660a636362383562643136316335636434653833643665383231376465383939
          66363566333332356334353132633564633936663364356666613162386639316464
grafana_user_vbb_email: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65306136623063393932333231356362366632656131616536323034363034336230376534663831
          6463313563316265323135643235313635333431396162380a306432646365366338626339386564
          34393733643036663539613332643036613431646637363031623132393061373138333561353161
          6333393632653337650a613232303734633164316135396130653637356630396637613832626665
          36346563323035656437653362653366643536636636386666336438303038313261
grafana_user_marzieh_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30343664306438653536396436346136626230376166396564653231646132346139333961666263
          3032316334356237373236613731376536656561323663330a313133323366383261653336616365
          64313338366133316133343830356166353066343762386464653262633764383365336266376633
          6334336565306530650a613832623832383038613534316537613234306335363631303462393039
          63633938623861663032323138356264333239333232633533343837333461666134
grafana_user_marzieh_email: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65346135646238373732353966616539303732656561386631646132303431326537346339366130
          6533323363313834316264636162363131343164316130620a626532633234353532616161613263
          32633261613232646135313364616233376162313365626464306262613366643062646262323763
          3766313238646238620a366231636564643466306432316539636366653933633863663466353131
          62643233656564616437653136626533346337643137306661663636386130393137

alerts_public_transport_slack_webhook: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32656337626466616364363064346664643138326266316662313166613461663435343132613863
          6439656439373465303434386534303938306662653132660a643765646636656532626662626234
          34643136353736616165623633363834383562656438616235313334323539646336343566373365
          6161333830353530300a633330376533356661343065656464386131653666383833316430323137
          30393765383566663635383932316562373963316438333236656461636236386438383031323265
          64633165363930396435313635623830636636356466313964333636613032653436363463666165
          35626337613565376366346466336363333066323736636133633530346565373766656433363962
          30663061343236336139
